version: 1.0.{build}
branches:
  only:
    - main

init:
  - cmd: git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: CleanRazor.Templates.csproj
  version: "{version}"
  version_prefix: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

build_script:
  - ps: ./build.ps1
