version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - main

init:
  - cmd: git config --global core.autocrlf true

image: Visual Studio 2022

dotnet_csproj:
  patch: true
  file: .\CleanRazor.Templates.csproj
  version: "{version}"
  version_prefix: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

build_script:
  - ps: ./build.ps1

test: off
